name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set environment variable
      run: echo "RED_HOME=$(pwd)" >> "$GITHUB_ENV"
    - name: Build
      run: cargo build --release
    - name: upload
      uses: actions/upload-artifact@v4
      with:
        path: target/release/red
        compression-level: 9
    - name: Publish GitHub release
      uses: softprops/action-gh-release@v2
      with:
        draft: true
        files: "target/release/red"
        if: startsWith( github.ref, 'refs/tags/' )
      
